name: advanced_ui
description: "advanced_ui"
publish_to: "hamazah_cll"


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_bloc: ^8.0.0
  path_drawing: ^1.0.1
  animations: ^2.0.7
  cached_network_image: ^3.2.1
  motion_toast: ^2.7.8
  shared_preferences: ^2.0.11
  lottie: ^2.4.0
  cupertino_icons: ^1.0.6
  flutter_zoom_drawer: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/photo/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500

